// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 20/05/2026, 15:43:38
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/pedro/Documents/VS-Code-Projects/Freela/lemon/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/pedro/Documents/VS-Code-Projects/Freela/lemon/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/pedro/Documents/VS-Code-Projects/Freela/lemon/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/pedro/Documents/VS-Code-Projects/Freela/lemon/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/pedro/Documents/VS-Code-Projects/Freela/lemon/plugins/**/*.{js,ts,mjs}","C:/Users/pedro/Documents/VS-Code-Projects/Freela/lemon/composables/**/*.{js,ts,mjs}","C:/Users/pedro/Documents/VS-Code-Projects/Freela/lemon/utils/**/*.{js,ts,mjs}","C:/Users/pedro/Documents/VS-Code-Projects/Freela/lemon/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/pedro/Documents/VS-Code-Projects/Freela/lemon/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/pedro/Documents/VS-Code-Projects/Freela/lemon/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/pedro/Documents/VS-Code-Projects/Freela/lemon/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;